### PR TITLE
Adding community info

### PR DESCRIPTION
**Pull request by ektaarora16**
Adding community info in open source community folder for hacktoberfest contribution.

### CODE REVIEW

**Comment by PulkitSinghDev** [comment]
please resolve conflicts @ektaarora16

**Comment by ektaarora16** [comment]
Okk

**Comment by ektaarora16** [comment]
Please check it again.

**Comment by PulkitSinghDev** [comment]
it's not updated with actual source, pls do it ASAP or I need to close this PR and you would need to do it again :)

**Comment by PulkitSinghDev** [comment]
nope, it's not updated correctly

**Comment by ektaarora16** [comment]
Conflicts resolved . Please check it out once.

**Comment by ektaarora16** [comment]
I have resolved the issue..now you can check it

**Comment by PulkitSinghDev** [comment]
just resolved it from my own side

**Pull request merged**
